name: Learning Github action

on: 
  workflow_dispatch
  # push:
  #   branches:
  #     - main 

jobs:
  start-job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say Hello
        run: |
            echo "Hello"
            apt update
      - name: install packages
        run: sudo apt install docker -y